### ISSUE TITLE
ASK: Is it possible to dynamically change the 'autobuild breadcrumb' font color tobe like manual style?

### ISSUE THREAD

**Issue by HenryKim2022** [GeekLabsUK/CI4-Breadcrumbs#5]
@GeekLabsUK 
**Autobuild**:
![image](https://user-images.githubusercontent.com/119053402/210719024-436f1d13-fcc8-4588-8fbb-a53ee3815874.png)

**Manual**:
![image](https://user-images.githubusercontent.com/119053402/210719683-550bc1c0-7ff8-4e85-8738-173a15e1b4cb.png)

**Comment by GeekLabsUK** [comment]
in the Config.php change the 

`public $clickable = 'true';`

to

`public $clickable = 'false';`

**Comment by HenryKim2022** [comment]
![image](https://user-images.githubusercontent.com/119053402/210822349-fc3f9e21-c31e-4e6e-a7ff-5fea7afe9e95.png)

Seems look same for me, wheter i turn $clickable = 'false'; or vice versa... nothing changed

**Comment by GeekLabsUK** [comment]
Sorry my mistake. The 

`public $clickable = 'true';`

should be 

`public $clickable = true;`

we need to remove apostrophes as this was sending a string to the library and not a boolean as expected.

**Comment by HenryKim2022** [comment]
It's working now 🤭
![image](https://user-images.githubusercontent.com/119053402/211048315-7b4b03ee-42f2-444c-8543-7aa91a85a678.png)

Thanks 4 your instructions 😁
